CREATE DATABASE IF NOT EXISTS biblioteca_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE biblioteca_db;

CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  phone VARCHAR(40),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  author VARCHAR(180) NOT NULL,
  isbn VARCHAR(40) UNIQUE,
  totalQuantity INT NOT NULL DEFAULT 1,
  availableQuantity INT NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Loan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  bookId INT NOT NULL,
  loanDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expectedReturnDate DATETIME NOT NULL,
  actualReturnDate DATETIME NULL,
  status ENUM('ACTIVO','DEVUELTO','VENCIDO') NOT NULL DEFAULT 'ACTIVO',
  fineAmount DECIMAL(10,2) NOT NULL DEFAULT 0,
  INDEX idx_loan_user (userId),
  INDEX idx_loan_book (bookId),
  INDEX idx_loan_status (status),
  CONSTRAINT fk_loan_user FOREIGN KEY (userId) REFERENCES User(id),
  CONSTRAINT fk_loan_book FOREIGN KEY (bookId) REFERENCES Book(id)
);
